name: Java

on:
  push:

jobs:
  Ant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Prepare
        run: find -L / -name "*.jar" 2>/dev/null | grep -P '(junit|hamcrest)'
      - name: Run the Ant 'junit' target
        run: ant -noinput -buildfile build.xml junit
      - name: Debug
        run: ls -lAh build
